// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPitoA6wyQuRfCtvVwXuku7RQsw-IBac',
    appId: '1:420496606770:web:104f0847d0e7ba58059e2b',
    messagingSenderId: '420496606770',
    projectId: 'doctor-a50da',
    authDomain: 'doctor-a50da.firebaseapp.com',
    storageBucket: 'doctor-a50da.firebasestorage.app',
    measurementId: 'G-GXRJB8MDE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChJZMbvrsW__OoeqDcTjhhGK18xWyln0U',
    appId: '1:420496606770:android:8935821cd6f8cfe2059e2b',
    messagingSenderId: '420496606770',
    projectId: 'doctor-a50da',
    storageBucket: 'doctor-a50da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnojoASk2rjPvfj_gfMEamv37bn1aidYQ',
    appId: '1:420496606770:ios:f538e05a4aef54b6059e2b',
    messagingSenderId: '420496606770',
    projectId: 'doctor-a50da',
    storageBucket: 'doctor-a50da.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnojoASk2rjPvfj_gfMEamv37bn1aidYQ',
    appId: '1:420496606770:ios:fe8e71fd5b03283f059e2b',
    messagingSenderId: '420496606770',
    projectId: 'doctor-a50da',
    storageBucket: 'doctor-a50da.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp.RunnerTests',
  );
}
